version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  my_app:
    build: ./app
    ports:
      - 1234:80
    volumes:
      - ./app:/user/src/app
    depends_on:
      - postgres

  postgres:
    restart: 'always'
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_PASSWORD=postgres"
    build: ./db