CREATE TABLE public."locations" (
"id" SERIAL,
"name" VARCHAR(200) NULL DEFAULT NULL,
"address" TEXT NULL DEFAULT NULL,
"type" VARCHAR(15) NULL DEFAULT NULL,
"created" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
